export enum DACommandType {
  MOVE_CROSSHAIRS_LEFT = 'MOVE_CROSSHAIRS_LEFT',
  MOVE_CROSSHAIRS_RIGHT = 'MOVE_CROSSHAIRS_RIGHT',
  MOVE_CROSSHAIRS_UP = 'MOVE_CROSSHAIRS_UP',
  MOVE_CROSSHAIRS_DOWN = 'MOVE_CROSSHAIRS_DOWN',
  CREATE_NEW_NODE = 'CREATE_NEW_NODE',
  INSERT_CHAR = 'INSERT_CHAR',
  EXIT_LABEL_EDIT_MODE = 'EXIT_LABEL_EDIT_MODE',
  MULTI_ITEM_SELECT = 'MULTI_ITEM_SELECT',
  ZOOM_IN = 'ZOOM_IN',
  ZOOM_OUT = 'ZOOM_OUT',
  CONNECT_SELECTED_NODES = 'CONNECT_SELECTED_NODES',
  SINGLE_ITEM_TOGGLE_SELECT = 'SINGLE_ITEM_TOGGLE_SELECT',
  RECENTER_VIEW = 'RECENTER_VIEW',
  RECENTER_CROSSHAIRS = 'RECENTER_CROSSHAIRS',
  UNSELECT_ALL = 'UNSELECT_ALL',
  ENTER_DRAG_MODE = 'ENTER_DRAG_MODE',
  DRAG_SELECTED_LEFT = 'DRAG_SELECTED_LEFT',
  DRAG_SELECTED_RIGHT = 'DRAG_SELECTED_RIGHT',
  DRAG_SELECTED_UP = 'DRAG_SELECTED_UP',
  DRAG_SELECTED_DOWN = 'DRAG_SELECTED_DOWN',
  EXIT_DRAG_MODE = 'EXIT_DRAG_MODE',
  ADD_WAYPOINT = 'ADD_WAYPOINT',
  TOGGLE_WAYPOINT_VISIBILITY = 'TOGGLE_WAYPOINT_VISIBILITY',
  DELETE = 'DELETE',
  ADD_LABEL = 'ADD_LABEL',
}

export type DACommand =
  | {kind: DACommandType.MOVE_CROSSHAIRS_LEFT}
  | {kind: DACommandType.MOVE_CROSSHAIRS_RIGHT}
  | {kind: DACommandType.MOVE_CROSSHAIRS_UP}
  | {kind: DACommandType.MOVE_CROSSHAIRS_DOWN}
  | {kind: DACommandType.CREATE_NEW_NODE}
  | {kind: DACommandType.INSERT_CHAR, value: string}
  | {kind: DACommandType.EXIT_LABEL_EDIT_MODE}
  | {kind: DACommandType.MULTI_ITEM_SELECT}
  | {kind: DACommandType.ZOOM_IN}
  | {kind: DACommandType.ZOOM_OUT}
  | {kind: DACommandType.CONNECT_SELECTED_NODES}
  | {kind: DACommandType.SINGLE_ITEM_TOGGLE_SELECT}
  | {kind: DACommandType.RECENTER_VIEW}
  | {kind: DACommandType.RECENTER_CROSSHAIRS}
  | {kind: DACommandType.UNSELECT_ALL}
  | {kind: DACommandType.ENTER_DRAG_MODE}
  | {kind: DACommandType.DRAG_SELECTED_LEFT}
  | {kind: DACommandType.DRAG_SELECTED_RIGHT}
  | {kind: DACommandType.DRAG_SELECTED_UP}
  | {kind: DACommandType.DRAG_SELECTED_DOWN}
  | {kind: DACommandType.EXIT_DRAG_MODE}
  | {kind: DACommandType.ADD_WAYPOINT}
  | {kind: DACommandType.TOGGLE_WAYPOINT_VISIBILITY}
  | {kind: DACommandType.DELETE}
  | {kind: DACommandType.ADD_LABEL}

