#+title: Current Homepage Criticism

At the end of the first video, there's a bit where you are focused on the link to the "A WIP experiment".  This seems extraneous and should be cut.  Also in this video, when focused on "Keyboard-oriented", the background grid for about the right third of the captured area seems to be missing.  Can we also change "A WIP experiment" to just "WIP experiment?"  But don't bother updating the subsequent videos just yet--I'm going to review those as well.

You have that weird thing, again, in the second video where a bunch of the background grid is missing, this time from around "Efficieny" when that node is focused upon/highlighted (second number 17 of the video).  I'm also noticing an effect where, as you are zooming in on a newly created node to highlight, you can still see the smaller, zoomed out new node, on top of the bigger one (see around second 21).  Also, it looks like you just captured a smaller area of the screen, rather than zooming in with the zoom/pan submenu.  You might also use the z key a couple times here to really focus on the node (as well as demonstrate the ability to hide the menus).  There also seems to be some unnecessary movements (maybe just zooming in or out too far, and then going back), after creating "Get both text and connections down..." and having gone back to the "Efficiency" node (around second 40 in the video).  And you aren't going directly to the spot where you end up placing the "Navigation" node.  And I really don't know what we are looking at immediately after creating the "Explore the keybindings, without..." node -- seems to be just empty space in the graph.

At the start of the 3rd video, you seem to be meandering back to the KiDraw root node.  It also feels a bit too zoomed out here--the zoomed up ghost nodes hide the edges we are traversing.  After adding "Vi-style modal text editing", demonstrate the i key (Edit Text) by going into that node and editing the text so that it says "Text editing with vi(m) modes and bindings".  Make sure you actually use visual mode, to cut/copy/paste/move by word/replace character/etc.

I'm noticing that the playback bar, and play button and so forth, at the bottom of each video gets in the way of the mode indicator when the video is paused.  Can we do something about that?  Is there maybe a css setting, or a bit of javascript, we can use to lower those controls to be underneath the actual video?

In the 4th video, we are again zoomed out a bit too much at the beginning.  Also, after waypoints for fine tuning, can we go back to the a->b, c graph and demonstrate adding and moving a waypoint?  Also, for the demonstration of Node/edge layout, can we do something that will be a bit more interesting than a straight line when the Force layout is applied?  And maybe have a DAG rather than a tree here?  I think (in quasi graphviz/dot notation), "a->b, b->c, a->c, d->b, d->c" should work out as a good example.  Also, we should have an example of "Coarse and fine movement", probably going back to that example.  I guess we should also do demos of Node/edge styling, and Edge labels, after their respective nodes are added.  The last little bit of the video can be cut--maybe just zoom out and recenter at the very end.

